name: "Quality Assurance"
on: [push]
jobs:
  "Lint":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - run: yarn install
      - name: "yarn run gatsby build"
        run: |
          # The sed part of this command removes terminal escape codes.
          OVERRIDE_NODE_ENV=development yarn run gatsby build 2> >(tee /dev/stdout | sed $'s/\e[^a-z]*[a-z]//g' > err.log)
      - run: |
          ! grep ^ err.log
      - name: "Dirty check"
        run: |
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
            PAGER= git diff --cached
            exit 1
          fi
      - name: yarn run eslint .
        run: |
          yarn run eslint . |& tee lint.log
          ! grep problem lint.log
